### ISSUE TITLE
Unable to replicate libgodot xcframework configuration

### ISSUE THREAD

**Issue by tishin** [migueldeicaza/SwiftGodotKit#14]
I'm trying to make an update for `libgodot.xcframework` based on 4.1.3 release of Godot, but I can't replicate the current xcframework architecture-wise.
The current release has a universal `arm64_x86_64` dylib inside, but when I compile libgodot using the command from readme:
`scons target=template_debug dev_build=yes library_type=shared_library debug_symbols=yes`
it makes a dylib only for the architecture of the host (in my current case - `arm64`, haven't checked it on an Intel Mac).

Godot doesn't seem to support `arm64_x86_64`:
```
scons target=template_debug dev_build=yes library_type=shared_library debug_symbols=yes arch=arm64_x86_64
scons: Reading SConscript files ...

scons: *** Invalid value for option arch: arm64_x86_64.  Valid values are: ['auto', 'x86_32', 'x86_64', 'arm32', 'arm64', 'rv64', 'ppc32', 'ppc64', 'wasm32']
```

Making separate builds for `arm64` and `x86_64` will result in a different xcframework configuration, and `make-libgodot.framework` doesn't support multiple dylibs, so I don't think that's how the current release was made.

Am I missing something here?

**Comment by tishin** [comment]
Found the answer in Godot docs: https://docs.godotengine.org/en/stable/contributing/development/compiling/compiling_for_macos.html

> To support both architectures in a single "Universal 2" binary, run the above two commands and then use lipo to bundle them together:
> 
> ```lipo -create bin/godot.macos.tools.x86_64 bin/godot.macos.tools.arm64 -output bin/godot.macos.tools.universal```

This also works for dylibs:
```lipo libgodot.macos.template_debug.dev.arm64.dylib libgodot.macos.template_debug.dev.x86_64.dylib -output libgodot.macos.universal.dylib -create```

**Comment by migueldeicaza** [comment]
I use this script:

scripts/make-libgodot.xcframework 

Does that help?
