### ISSUE TITLE
4.2 on Mac: failure

### ISSUE THREAD

**Issue by migueldeicaza** [migueldeicaza/SwiftGodotKit#16]
In the 4.2 branch, I have not managed to get the libgodot powered by 4.2 to work at all.

It produces Vulkan errors with `swap_buffers` as soon as it starts up, even if running as a standalone does not have this problem.

**Comment by tishin** [comment]
What are you trying to run using libgodot? I don't seem to have any issues running TrivialSample in the 4.2 branch on arm64. All tests from SwiftGodot repo also pass successfully using the new xcframework.

**Comment by tishin** [comment]
I also checked TrivialSample in 4.2 branch on an Intel Mac, no issues either.

**Comment by migueldeicaza** [comment]
Thank you for checking.

I was getting this error, and then all of a sudden it vanished, but I did not do anything.   I am afraid that this might be a race condition (that is what it looks like from the Godot bug reports).
