### ISSUE TITLE
StandaloneExample fails to build on macOS without removal of `@Godot`

### ISSUE THREAD

**Issue by hwjeremy** [migueldeicaza/SwiftGodotKit#19]
Hi everyone,

While attempting to reproduce a behaviour in a minimal project, I found I was unable to build Standalone Example.

**The procedure followed:** 

1. Clone SwiftGodotKit fresh
2. "Trust & Enable" plugins
3. [Await package resolution]
4. Build via "Run"

**Result:**

Build failure, "Unknown attribute 'Godot'".

[Run-StandaloneExample-2023.12.28_14-26-32-+1100.xcresult.zip](https://github.com/migueldeicaza/SwiftGodotKit/files/13783038/Run-StandaloneExample-2023.12.28_14-26-32-%2B1100.xcresult.zip)

<img width="960" alt="Screenshot 2023-12-28 at 14 30 43" src="https://github.com/migueldeicaza/SwiftGodotKit/assets/7691451/e2937074-0c4a-4008-a89a-ef9b62c80efb">

Curiously, removing `@Godot` and re-running allows the project to build and run successfully:

<img width="840" alt="Screenshot 2023-12-28 at 14 33 03" src="https://github.com/migueldeicaza/SwiftGodotKit/assets/7691451/8490ae2b-89f6-4860-9277-64eba5d7131c">

**Environment:**

macOS 14.2
Xcode 15.0.1
Swift version 5.9
Macbook Pro 16 w/ M2 Max

**Comment by migueldeicaza** [comment]
Ah yes, that has some very old hardwired dependencies, updating the sample

**Comment by migueldeicaza** [comment]
Fixed by bumping the referenced versions. thanks for the bug report!~
