### ISSUE TITLE
Outdated SwiftGodot dependency

### ISSUE THREAD

**Issue by tishin** [migueldeicaza/SwiftGodotKit#21]
I'm a bit puzzled with this commit:
https://github.com/migueldeicaza/SwiftGodotKit/commit/a7f90ce4fa3e20fa95b57f1d95704445e5844d3d
It updates SwiftGodot dependency from https://github.com/migueldeicaza/SwiftGodot/commit/245b20d43b85d8280a2a99a24b9c6f4f9058e8f2 (Nov 5, 2023) to a much older https://github.com/migueldeicaza/SwiftGodot/commit/1359586f2332d500d30661158e062a0e9f97751c (Sep 2, 2023)

This makes SwiftGodotKit samples unbuildable. They use `GDictionary`, and (I assume) early September version of SwiftGodot didn't have it yet.

**Comment by migueldeicaza** [comment]
This was definitely a mistake on my end, and I copy pasted the wrong place - I was trying to fix the StandaloneExample requiring macros (it was updated to use macros, but depended on the old September SwiftGodot that did not have them).
