### ISSUE TITLE
Can't run it in macOS

### ISSUE THREAD

**Issue by alexanderthoren** [migueldeicaza/SwiftGodotKit#22]
I am using the `main` branch of the project exactly as explained in https://migueldeicaza.github.io/SwiftGodotDocs/tutorials/swiftgodot/using-swift-godot-kit. Whenever I try to run the project it crashes with the error `Thread 1: EXC_BREAKPOINT (code=1, subcode=0x1984150f8)` and these logs in the console:
* Message from debugger: killed
* Logging Error: Failed to initialize logging system. Log messages may be missing. If this issue persists, try setting IDEPreferLogStreaming=YES in the active scheme actions environment variables.
* Program ended with exit code: 9

Current macOS version 14.2.1 and Xcode 15.1 with Swift 5.9.2 (5.9.2.2.56).

**Comment by migueldeicaza** [comment]
Odd, that is the very configuration I use.   The first step would be to get a stack trace to figure out where the crash is happening.

**Comment by alexanderthoren** [comment]
I've already been able to run it a few weeks ago! Thanks for all the effort! I'll close this issue now 👍🏻
