### ISSUE TITLE
Noob question - how to run the TrivialSample

### ISSUE THREAD

**Issue by hyouuu** [migueldeicaza/SwiftGodotKit#3]
If I do `swift main.swift` then I get:
```
main.swift:10:8: error: no such module 'SwiftGodot'
import SwiftGodot
```

Do I create a Package.swift within the same folder or did I get this wrong completely?

Thanks!

**Comment by migueldeicaza** [comment]
Yes you need to have a Package.swift that references this module.

**Comment by hyouuu** [comment]
Could you provide an example file? I tried this:

```
// swift-tools-version:5.8
import PackageDescription

let package = Package(
    name: "Banban",
    platforms: [
        .macOS(.v12),
    ],
    dependencies: [
        .package(url: "https://github.com/migueldeicaza/SwiftGodotKit.git", branch: "main")
    ],
    targets: [
        .target(name: "App", dependencies: [
            .product(name: "SwiftGodotKit", package: "SwiftGodotKit"),
        ]),
        .executableTarget(name: "Run", dependencies: [
            .target(name: "App"),
        ]),
    ]
)
```

And calling `swift Package.swift` gives `Package.swift:2:8: error: no such module 'PackageDescription'`

For context I only have the `main.swift` & `Package.swift` in the folder
<img width="584" alt="Screenshot 2023-09-05 at 10 02 39 PM" src="https://github.com/migueldeicaza/SwiftGodotKit/assets/5061867/9145ad7d-44fd-42f0-84db-8cac3a8ed0f1">

Sorry I have only used Xcode's built in way to create projects and run them

**Comment by hyouuu** [comment]
mmm now I get this error - thoughts? It'll be greatly helpful if a Mac sample app is included 😄

<img width="538" alt="Screenshot 2023-09-06 at 10 50 51 AM" src="https://github.com/migueldeicaza/SwiftGodotKit/assets/5061867/2d162652-6d07-4ee3-9511-7254d254a6a6">

**Comment by migueldeicaza** [comment]
I added a standalone example to show how it works:

https://github.com/migueldeicaza/SwiftGodotKit/tree/main/StandaloneExample

And I packed a sample program with Xcode here:

https://tirania.org/tmp/SwiftGodotApp.tar.gz

**Comment by hyouuu** [comment]
Perfect thank you so much!!
