### ISSUE TITLE
Issue with Versioning

### ISSUE THREAD

**Issue by nschos** [migueldeicaza/SwiftGodotKit#30]
Hi! I am interested in using SwiftGodotKit to develop a game for the iOS and iPadOS platforms. I would like to use SwiftGodotKit within the SwiftUI lifecycle, with a UIViewRepresentable. I added the package as stated on GitHub, but it seems there is a versioning issue. I received the build error:

"The package product 'SwiftGodot' requires minimum platform version 15.0 for the iOS platform, but this target supports 12.0."

All settings are default and everything is properly updated. I don't know why this error message is appearing. Is there any additional step to correctly configure the library?
My Xcode version is 15.4 and the Swift version is 5.10. The iOS target is set to 17.5.
I just discovered SwiftGodot, so I'm just a beginner. Thank you in advance!

**Comment by migueldeicaza** [comment]
You need to set the minimum deployed version in your iOS project.
