### ISSUE TITLE
README should specify Swift 5.9 is required

### ISSUE THREAD

**Issue by mgrider** [migueldeicaza/SwiftGodotKit#5]
I really want to try this out, but I've run into a bunch of issues.

First, the issues I was able to resolve:
- As stated in the issue title: The readme should probably specify Swift 5.9 is required
  I first tried to get this working in Xcode 14.3.1, but the swift dependency wouldn't load for me. When I tried to re-import the package, only then did I get an error to this effect.
- The README should probably also link to the example project. (I found the link in a closed issue.)
- The example project also contains your Apple Team ID, FWIW. You might want to select "none" from the code signing dropdown and re-zip.

Where I'm stuck right now is with an error on line 9 of `main.swift` that says `No such module 'SwiftGodotKit'`.

I think it might be nice to have more detailed instructions on how to get this working in the README. I do also have a lot of questions. For instance, do I need a specific version of Xcode? How about Godot?

**Comment by migueldeicaza** [comment]
This is fabulous feedback, thanks!

1. I have updated the instructions as suggested, and will do the same for the SwiftGodot package as well.
2. Thanks for the suggestion on the sample, I have linked it.   I also wrote a tutorial for using with Xcode, but I think it needs to be prettified a bit, but the raw content is here: https://github.com/migueldeicaza/SwiftGodot/blob/main/Sources/SwiftGodot/SwiftGodot.docc/Tutorials/Using%20Swift%20Godot%20Kit.tutorial
3. I could not find my team ID, or a zip file with it :-)

The error is part of the way that Xcode works, those errors go away after the first build.
