### ISSUE TITLE
Regarding the space before () against Swift style convention

### ISSUE THREAD

**Issue by hyouuu** [migueldeicaza/SwiftGodotKit#6]
Hello! I noticed that the source code always put a space before `func`'s (), e.g. `init ()`, where as Swift convention is `init()` - could we adopt the convention?

**Comment by migueldeicaza** [comment]
Not really, it is a style I have used for a long time.

Might revisit this in the future when I adopt some sort of swift formatter, and do it all in one pass, but will take me time to continue my research.

**Comment by joshuapoq** [comment]
Love what you're doing here but I have to agree. The space goes against the Swift style guidelines and DocC symbol links.
